### ISSUE TITLE
allowlist same-origin domain

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec-feature-policy#107]
Why do we extend the set of places that use same-origin domain? Was this a mistake and should the HTML Standard carry a warning sign of sorts? (It probably should.)

cc @mikewest

**Comment by mikewest** [comment]
I don't know why matching is "same origin-domain". @clelland might.

**Comment by clelland** [comment]
The original discussion that led to this change was in https://github.com/whatwg/html/pull/2217 -- it looks like it was to bring it in line with the existing security boundaries for allowfullscreen/allowpaymentrequest.

**Comment by annevk** [comment]
Aaah, I remember now, so you run it at a time where `document.domain` could not possibly have been set? That's the one case where it ends up being stricter. It would be good to copy the examples over too that explain that.

**Comment by clelland** [comment]
Closing this; the HTML spec has the note and examples as requested, and there's recent discussion in #253 about whether we should change this, and switch to same-origin checks.
