### ISSUE TITLE
Explicit export/definition for "payment"

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webappsec-feature-policy#154]
Would be great to `"<dfn export>payment</dfn>"` token (or however BS does it) so we can link to it directly from the Payment Handler spec.

**Comment by clelland** [comment]
This feature is properly defined now in [payment-request](https://www.w3.org/TR/payment-request/#feature-policy) (as of https://github.com/w3c/payment-request/pull/822), so any links from Payment Handler should be updated to point to that definition.
