### ISSUE TITLE
Feature-Identifier value for WebAuthn?

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webappsec-feature-policy#168]
(framed?) webapps may request permission to use the PaymentRequest interface via the [feature-policy](https://wicg.github.io/feature-policy/) [feature-identifier value](https://github.com/w3c/webappsec-feature-policy/blob/master/features.md) `payment`.  

Given the desire for webauthn to be usable in a webpayment context and its being a "powerful feature", ought we mint a `webauthn` [feature-identifier value](https://github.com/w3c/webappsec-feature-policy/blob/master/features.md) ?

see also #166,  #75, w3c/webauthn#911

**Comment by subyraman** [comment]
@equalsJeffH @clelland has there been any movement on this in recent months? The WebAuthn spec indicates that Feature Policy could be used for whitelisting WebAuthn interactions inside of cross-origin iframes; as an authentication provider this is behavior we'd like enable for our users.

https://w3c.github.io/webauthn/#createCredential

**Comment by equalsJeffH** [comment]
yes: https://github.com/w3c/webauthn/issues/911#issuecomment-486394287 specifically.  just opened FP PR #306

**Comment by equalsJeffH** [comment]
update: see [section 5.9. Feature Policy integration](https://w3c.github.io/webauthn/#sctn-feature-policy) in current webauthn editor's draft.  May we please now  mint a `webauthn` [feature-identifier value](https://github.com/w3c/webappsec-feature-policy/blob/master/features.md) ?

**Comment by equalsJeffH** [comment]
This was done in https://github.com/w3c/webappsec-feature-policy/pull/306
