### ISSUE TITLE
Consider moving to Web App Sec?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webappsec-feature-policy#218]
It seems this API is starting to get quite a bit of traction: Looking at caniuse.com, it's partially or fully implemented in Chrome and Safari, and I've just been informed it's landing in Firefox - which is really amazing! 

Have you all thought about moving this work to Web App Sec for formal standardization or do you feel it still needs more incubation? 

For specs that rely on this spec (e.g., Payment Request), it would be great to have this in a WG.  

Cc'ing WICG chairs @yoavweiss and @cwilso.

**Comment by mikewest** [comment]
If it's helpful to y'all, WebAppSec is probably as good a home as any (and I think FP fits into the existing charter). @wseltzer and @dveditz might also have opinions.

**Comment by clelland** [comment]
I think the spec is in a pretty stable state; there may be a few issues to iron out around the JS API, and usage in workers, but otherwise I think it's in a good place, and probably time to think about making it a real standard.

(Especially now that it's being referenced by other specs, and the HTML integration has landed at WHATWG)

**Comment by marcoscaceres** [comment]
Ok, this is great to hear. Will wait for word from @wseltzer and @dveditz.

**Comment by clelland** [comment]
It sounds like the conclusion from the WebAppSec teleconference was to discuss this at TPAC in October.

**Comment by marcoscaceres** [comment]
Thanks for the update. Let’s come back to this during TPAC.

**Comment by clelland** [comment]
Move completed. There are still some dangling links on docs that need to be addressed, but there's a redirect from the old repo to the new one which should help with some of them (thanks, @yoavweiss!)
