### ISSUE TITLE
export anchor terms for algorithms

### ISSUE THREAD

**Issue by frivoal** [w3c/webappsec-feature-policy#260]
The https://wicg.github.io/feature-policy/#is-feature-enabled algorithm (and maybe others) are useful to refer to form outside this spec. In addition to giving it a section title, giving it an exported `<dfn>` would make cross linking easier from bikeshed and the like.

**Comment by clelland** [comment]
Should all of the algorithms be exported? The only ones that I think are currently used as entry points from outside specs are
 - Initialize document’s Feature Policy
 - Initialize document’s Feature Policy from response
 - Is feature enabled in document for origin?
 - Generate report for violation of feature policy on settings
 - Should request be allowed to use feature?

The others could be internal to this doc, I think.

**Comment by annevk** [comment]
I'd try to be conservative with exporting and only do so when requested (or have identified a need) as there's no good tooling for updating downstream dependencies (or even identifying them).

**Comment by clelland** [comment]
SGTM. I'll add *Is Feature Enabled* and *Generate Report*, as those are the two which are expected to be used externally. The *Initialize* methods are used from HTML, but it has its own biblio entries for them.
