### ISSUE TITLE
The key of report.body.feature doesn't match docs

### ISSUE THREAD

**Issue by ScottHelme** [w3c/webappsec-feature-policy#268]
Looking at the Chrome test cases for FP Reporting I see the following:

```
var check_report_format = (reports, observer) => {
 let report = reports[0];
 assert_equals(report.type, "feature-policy");
 assert_equals(report.url, document.location.href);
 assert_equals(report.body.feature, "geolocation");
```

In `reporting.md` the `report.body.featureId` key is used:

https://github.com/w3c/webappsec-feature-policy/blame/master/reporting.md#L47

**Comment by clelland** [comment]
See #267 -- I think that the two Chromium commits mentioned there should have updated these identifiers as well, to bring Chrome and WPT in line with the spec and with `reporting.md`.

In my local checkout, I don't see any instances of `report.body.feature` any more, in the `web_tests/external/wpt/feature-policy/reporting` directory at least. If I've missed one, let me know and I'll take care of it right away.

**Comment by ScottHelme** [comment]
Ah yes, my lack of familiarity with the code, looks good!
