### ISSUE TITLE
Feature-Policy-Report-Only: which types are supported?

### ISSUE THREAD

**Issue by gi11es** [w3c/webappsec-feature-policy#305]
In Chrome 74 with the origin trial sync-xhr works, but for example is I try to use document-write or unsized-media, I get a developer console error:

```
Error with Feature-Policy-Report-Only header: Unrecognized feature: 'document-write'.
Error with Feature-Policy-Report-Only header: Unrecognized feature: 'unsized-media'.
```

I can't find a list of which feature policy types are currently supported in report-only mode.

**Comment by maxtruxa** [comment]
Implemented feature policies are already documented [here](https://github.com/w3c/webappsec-feature-policy/blob/master/features.md). The values described are valid for `Feature-Policy` as well as `Feature-Policy-Report-Only`.

Note that the authoritative list of which policies are actually implemented is always the [source code](https://github.com/chromium/chromium/blob/master/third_party/blink/renderer/core/feature_policy/feature_policy_features.json5) ([permalink](https://github.com/chromium/chromium/blob/2d57e5b8afc6d01b344a8d95d3470d46b35845c5/third_party/blink/renderer/core/feature_policy/feature_policy_features.json5)).

The feature policies `document-write` as well as `unsized-media` are hidden behind the Chrome/Chromium flag `--enable-blink-features=ExperimentalProductivityFeatures`.

**Comment by gi11es** [comment]
Thanks!
