### ISSUE TITLE
define the term "feature"

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webappsec-feature-policy#309]
the term is essentially defined in the opening introduction, but would be good to put a \<dfn export>feature\</dfn> early on in there for specs depending on this spec. thx.

**Comment by clelland** [comment]
"Policy-controlled feature" is defined, and exported, and I think that should be the preferred term.

"Feature" is shorthand within the spec to avoid having to say "policy-contolled feaure" repetitively in prose. It's probably too generic a term to try to claim for just Feature Policy.
