### ISSUE TITLE
"Enforce" links (and "enforce" generally)

### ISSUE THREAD

**Issue by eeeps** [w3c/webappsec-feature-policy#312]
First, the word "Enforce" links out to the definition of that term in the CSP spec in both https://w3c.github.io/webappsec-feature-policy/#algo-initialize-for-document and https://w3c.github.io/webappsec-feature-policy/#algo-initialize-from-response.

That seems wrong, probably.

Zooming out – does this document need its own definition of "enforce?" It shows up occasionally, but I'm wondering if standardizing on talking about features being "enabled" or "disabled" would be a good idea. The distinction here is that "enabled"/"disabled" is a state to be read by other specs, which take this state into account and do the "enforcement" as a part of their processing steps.

**Comment by clelland** [comment]
That's a good catch -- in markup, it's just `<a>Enforce</a>`, I don't think the reference to CSP was deliberate. (Before #246, there was a different definition: Enforcing meant to set the policy as the policy for a document. Once that was removed, bikeshed went ahead and found an alternate defintion)

**Comment by eeeps** [comment]
Makes sense. "Set" seems more appropriate than "enabled"/"disabled", as a thing to replace the "enforces" with.

What algorithm should it link to, if any? [Merge directive with declared policy](https://w3c.github.io/webappsec-feature-policy/#algo-merge-directive-with-declared-policy)?

**Comment by clelland** [comment]
If we were to follow the initial spirit, we could probably just replace the last step of each of those documents with something like

* Set *document*'s **[feature policy](https://html.spec.whatwg.org/multipage/dom.html#concept-document-feature-policy)** to *policy*.

WDYT?

**Comment by eeeps** [comment]
Sounds good to me! ☝️
