### ISSUE TITLE
Add display-capture

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec-feature-policy#339]
It's added in https://w3c.github.io/mediacapture-screen-share/, but it's not in the registry.

https://w3c.github.io/permissions/#permission-registry has it as "display", but Mozilla considers that a bug and we want to use "display-capture" consistently (and generally avoid mismatches between permissions and feature policies).

**Comment by Malvoz** [comment]
I added this feature in https://github.com/w3c/webappsec-feature-policy/pull/323, yet to be merged.

> https://w3c.github.io/permissions/#permission-registry has it as "display"

It was changed to `display-capture` in https://github.com/w3c/permissions/pull/188, but they seem to have an issue with the Github page not reflecting that change.
