### ISSUE TITLE
Document Policy and Booleans

### ISSUE THREAD

**Issue by mikewest** [w3c/webappsec-feature-policy#356]
This is a nit, feel free to ignore it.

The `boolean-feature`/`no-boolean-feature` seems strange, especially when compared against the other kinds of features that rely on parameterizing the values. Did you consider something like `boolean-feature;enabled=?0` (where the absence of the parameter would be treated as `enabled=?1`? That seems more consistent with the others, and therefore simpler to parse. It's marginally more verbose, but also less confusing. :)

**Comment by clelland** [comment]
I'd considered that, or even something like `boolean-feature;false` or `boolean-feature;no` (using just tokens as parameter names, with no values needed).

One issue is that I expect that almost all of the time, document policy features will be generally allowed in all contexts, and so disabling the feature will be the most common use of an explicit policy directive. Given that, I was trying to optimize for intuitiveness of the 'disable' case, and hopefully improve on the feature-policy-style of `boolean-feature none`. Writing "`<iframe policy="no-scripts">`" seemed like the most straightforward way of expressing something like that.

Suggestions are welcome though; it's certainly not set in stone.

**Comment by mikewest** [comment]
How about `Document-Policy: enabled=(thing1;whatever=9 thing2;whatever=10), disabled=(script;really=?1)`? Dictionaries of lists of parameterized features?

**Comment by mikewest** [comment]
(I guess this starts getting verbose for the attribute case...)

**Comment by jpchase** [comment]
This is somewhat covered by the open TAG issue: https://github.com/w3ctag/design-reviews/issues/341#issuecomment-529816262

**Comment by clelland** [comment]
w3c/webappsec-permissions-policy#388 will address this, by making the header a dictionary; a key with no value will be implicitly true, and the `=?0` syntax, while not as easily readable as `no-`, will be an explicit false value.
