### ISSUE TITLE
Remove or replace `vr` in the examples

### ISSUE THREAD

**Issue by Malvoz** [w3c/webappsec-feature-policy#364]
https://w3c.github.io/webappsec-feature-policy/#frame-policies has an example with the `vr` feature identifier, which has been replaced with `xr-spatial-tracking` as defined by the WebXR Device API spec.

**Comment by clelland** [comment]
Closed by https://github.com/w3c/webappsec-feature-policy/commit/1365a8ee0daebe97ed6e8d0a67d53749aaa59fb8.
