### ISSUE TITLE
Document Policy Header as Dictionary

### ISSUE THREAD

**Issue by clelland** [w3c/webappsec-feature-policy#387]
Currently, the `Document-Policy` header is defined as a list of parameterized tokens, where the tokens are the feature names (or names preceded by 'no-' for false booleans), and their values require a name/value pair as a parameter.

Would it be better to use a dictionary as the underlying structure instead, with the value being the parameterized value (to avoid needing a synthetic name)? That would also open the possibility of parameter values being inner lists, so we could do things like (examples only; these aren't real policies yet):

```http
Document-Policy: allowed-animations=(width height opacity),
                 allow-navigation-to=(self "https://example.com"),
                 page-orientations=(portrait landscape)
```

For booleans, this would mean that true values would be expressed with just the name, while false ones would use "=?0".

```http
Document-Policy: scripts, sync-xhr=?0
```

Reporting would still be done with a parameter on the dictionary member:

```http
Document-Policy: max-image-bpp=2.0;report-to=endpoint
```

**Comment by annevk** [comment]
Does that mean that you get/have to configure a different reporting endpoint per token?

**Comment by clelland** [comment]
There is still a `*` token allowed, which is the fallback for any configurations that don't have a specific endpoint:

```http
Document-Policy: max-image-bpp=2.0, scripts=?0, *;report-to=default-endpoint
```

And you can use `none` as an endpoint name to cancel reporting for a feature if you set a default endpoint but don't want it used for a specific feature:

```http
Document-Policy: max-image-bpp=2.0;report-to=none, scripts=?0, *;report-to=default-endpoint
```

I think that's all covered by https://w3c.github.io/webappsec-feature-policy/document-policy.html#configure-reporting, but if its not, we should make it clear.

**Comment by clelland** [comment]
@annevk -- does the dictionary structure seem reasonable to you otherwise?

**Comment by annevk** [comment]
I think so. It's nice that it matches Permissions Policy.

**Comment by clelland** [comment]
Thanks! I'll merge and we can iterate if needed.
