### ISSUE TITLE
Provide example(s) of enabling disabled-by-default feature(s)

### ISSUE THREAD

**Issue by ddorwin** [w3c/webappsec-feature-policy#45]
The current [Examples](https://wicg.github.io/feature-policy/#examples) focus on disabling features. Since many features are disabled by default on nested contexts, there should be a clear example of this. The one example of enabling is somewhat advanced.

The following text from that example seems out of place, as if it was an intro to such an example: 
>Some features are disabled by default in embedded contexts. The enable policy allows the application to selectively enable such features for whitelisted origins.

**Comment by craigfrancis** [comment]
Maybe the spec could include a list of all policies, and show their nested context defaults?

The current list I've found is within the Chromium source code, and available as of Chrome 62 (to be released 17th October 2017):

https://cs.chromium.org/chromium/src/third_party/WebKit/Source/platform/feature_policy/FeaturePolicy.cpp?type=cs&q=GetDefaultFeatureNameMap&l=206

- camera
- encrypted-media
- fullscreen
- geolocation
- microphone
- midi
- payment
- speaker
- usb
- vr

And for those with FeaturePolicyExperimentalFeaturesEnabled:

- vibrate
- cookie
- domain
- docwrite
- sync-script
- sync-xhr

**Comment by clelland** [comment]
Closing this with a textual change to one of the examples, which was actually showing how to do this. (The original issue refers to a version of the spec which is no longer current, and the examples have evolved over time)

Re https://github.com/w3c/webappsec-feature-policy/issues/45#issuecomment-330200409: We now have https://github.com/w3c/webappsec-feature-policy/blob/master/features.md, which I believe includes all features spec'd or implemented (including those behind flags).
