### ISSUE TITLE
Feature proposal: opener

### ISSUE THREAD

**Issue by clelland** [w3c/webappsec-feature-policy#50]
Raised in https://github.com/whatwg/html/issues/2122#issuecomment-264024796, it might be possible to put a `noopener` policy into FP; rather than insisting that developers annotate every `<a>` tag. Something like:

    {"opener": ["self", "https://friendly-domain.com"]}

would make any links in the current page, except those to the whitelisted domains, behave as if the `rel=noopener` attribute was added.

This may be an abuse of the whitelist; we've only used it for policy propagation, rather than selectively changing behaviour of parts of the current document, but it might be worth discussing.

(Possibly another interesting thing about making this part of FP is that we could apply it to windows created with window.open as well, which isn't possible with an attribute on `<a>`.)

**Comment by zcorpan** [comment]
Please see https://github.com/w3c/webappsec/issues/139

**Comment by annevk** [comment]
This is https://github.com/whatwg/html/issues/3740 now.
