### ISSUE TITLE
Expose policy to javascript

### ISSUE THREAD

**Issue by clelland** [w3c/webappsec-feature-policy#65]
Currently the policy which is enforced for a document is pretty opaque to any script running in that document -- a script can try to use a feature and see if/how it fails, but but otherwise there's no good way to know whether or the doc has been denied access by policy, or (possibly importantly,) whether any frames you create will have access to a given feature.

I'd propose adding a member to Document (bikeshed-name: "policy") that simply includes a boolean value for each supported feature, indicating whether or not it is enabled for that document.

Example:

    document.policy => {
        "fullscreen": true,
        "payment": false,
        "vibrate": true
    }

For frames embedded in the doc, we shouldn't grant access to their final policy, I think -- it's a cross-origin information leak to tell whether a feature which was granted to a frame was declined through an HTTP header or not. Instead, we can expose the inherited policy for that frame -- being a combination of the parent page's own policy and the container policy (controlled by the parent,) this doesn't expose any cross-origin information, but lets sites easily answer the question of whether a feature has been granted to a given frame.

Example:

    var frame = document.querySelector("iframe#specific-frame");
    frame.policy => {
        "fullscreen": true,
        "payment": false,
        "vibrate": false
    }

(Original proposal doc: https://docs.google.com/document/d/1xHEbR9ZTbHNqY9ituKKDxoZQbOZ3rpLfJ37U_JagdR4/edit#heading=h.28unziaa7fjg)

**Comment by LoonyBean** [comment]
New proposal doc: https://docs.google.com/a/chromium.org/document/d/1wvk3cXkblNnbkMcsKayseK-k0SMGiP9b9fQFgfpqQpc/edit?usp=sharing

**Comment by foolip** [comment]
@clelland this was fixed by https://github.com/w3c/webappsec-feature-policy/pull/184, right? Then later renamed in https://github.com/w3c/webappsec-feature-policy/pull/262 to give the current API:
https://w3c.github.io/webappsec-feature-policy/#the-policy-object

**Comment by clelland** [comment]
Yes, this is definitely closable now.

**Comment by annevk** [comment]
Well, some of this will need changes no?
